# docker-compose.yml 
services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    stdin_open: true # Keeps stdin open to allow for input
    tty: true        # Allocates a pseudo-TTY
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  postgres_data: