# This is the main configuration file for your dbt project.

name: 'telegram_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which folder dbt will look for models in.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:        # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configure profiles to be used by dbt
profile: 'telegram_analytics'

models:
  telegram_analytics:
    # Configures models under the marts/ folder
    marts:
      # --- FIX: Add this line to build models in the 'marts' schema ---
      +schema: marts
      +materialized: table # Marts will be created as tables
    # Configures models under the staging/ folder
    staging:
      +materialized: view # Staging models will be created as views
